### ISSUE TITLE
Date timezone is not set for CLI

### ISSUE THREAD

**Issue by jmverges** [FluidTYPO3/FluidTYPO3-Vagrant#12]
I'm getting this error running the UT for Flux:

The data provider specified for FluidTYPO3\Flux\Tests\Unit\Transformation\FormDataTransformerTest::testTransformation is invalid.
DateTime::__construct(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone.

**Comment by xf-** [comment]
```bash
php -i | grep date.timezone
date.timezone => Europe/Berlin => Europe/Berlin
```
Should be fixed in next commit
