### ISSUE TITLE
Reason: File "browser.php" was not found (2)! 

### ISSUE THREAD

**Issue by jmverges** [FluidTYPO3/FluidTYPO3-Vagrant#13]
@xf- what do you think?

https://github.com/FluidTYPO3/flux/issues/1153

https://github.com/TYPO3/TYPO3.CMS/commit/f00efef1bd93181fe1c594bf169cd8ccb6eb7f63

**Comment by jmverges** [comment]
I think this could work:
rewrite ^(.*/)(ajax|alt_clickmenu|alt_db_navframe|alt_doc|alt_file_navframe|browser|db_new|dummy|init|login_frameset|logout|mod|move_el|show_item|tce_db|tce_file|thumbs)\.php$ $1deprecated.php last;

**Comment by NamelessCoder** [comment]
Closing this one - looks like we found a solution, see followups.
