### ISSUE TITLE
Ubuntu 14.04: Failed to mount folders in Linux guest. (How to fix)

### ISSUE THREAD

**Issue by jmverges** [FluidTYPO3/FluidTYPO3-Vagrant#4]
Hi there,
since the other day I'm experimenting this problem when I clone the repo and I do a vagrant up:

# Failed to mount folders in Linux guest. This is usually because the "vboxsf" file system is not available. Please verify that the guest additions are properly installed in the guest and can work properly. The command attempted was:

mount -t vboxsf -o uid=`id -u vagrant`,gid=`getent group vagrant | cut -d: -f3` vagrant /vagrant
mount -t vboxsf -o uid=`id -u vagrant`,gid=`id -g vagrant` vagrant /vagrant

The error output from the last command was:

stdin: is not a tty
mount: Protocol error

## The following lines can fix it if you are experimenting the same problem:

class HackyGuestAdditionsInstaller < VagrantVbguest::Installers::Ubuntu
  def install(opts=nil, &block)
    super
    super_garbage_hack = <<-EOF
if [ ! -e /usr/lib/VBoxGuestAdditions ]; then
  sudo ln -s /opt/VBoxGuestAdditions-4.3.10/lib/VBoxGuestAdditions \
    /usr/lib/VBoxGuestAdditions || true
fi
EOF
    communicate.sudo(super_garbage_hack)
  end
end

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    config.vbguest.installer = HackyGuestAdditionsInstaller
...

**Comment by xf-** [comment]
Hi,

do you use the guest plugin installer?

I will test it the next days on my system. Looks like puphpet updated finally the box to a newer debian 7.8.

**Comment by jmverges** [comment]
Hi, 

yes I'm using it and yes, puppet updated the box. 
Let me know.

**Comment by xf-** [comment]
Hi,

works fine on my system. I don't use vbguest vagrant plugin, because the puphpet box has already vbguest plugin.

Current installed software
core/linux 3.18.6-1 (base)
core/linux-api-headers 3.18.5-1
core/linux-firmware 20150206.17657c3-1
community/vagrant 1.7.2-2
community/virtualbox 4.3.20-5
community/virtualbox-guest-iso 4.3.20-1
community/virtualbox-host-modules 4.3.20-8

On another machine 3.19 kernel and it works.

**Comment by jmverges** [comment]
okey, let me check if the problem is vguest plugin

**Comment by jmverges** [comment]
Confirmed, the problem is in vguest plugin.
