### ISSUE TITLE
[TASK] Composer and typo3_console?

### ISSUE THREAD

**Issue by jmverges** [FluidTYPO3/FluidTYPO3-Vagrant#7]
This is just an idea but could be great to delegate the code in charge to TYPO3 installation and FluidTYPO3 extensions to composer and typo3_console, what do you think?

**Comment by xf-** [comment]
No composer support.
The problem is after 50 downloads from one IP per hour you need to add a token for github API

**Comment by xf-** [comment]
With TYPO3 broken cli installer we need to evaluate this option again.
(Autoloader won't update and throws errors).

**Comment by jmverges** [comment]
Xaver, it is working quite nice to me: https://github.com/SimpleTYPO3/SimpleTYPO3-Vagrant/blob/master/puppet/modules/typo3/manifests/init.pp

**Comment by xf-** [comment]
i think dev-master is no option. 6.2 is next stable cms distribution stuff

**Comment by jmverges** [comment]
It refers to https://github.com/SimpleTYPO3/typo3-cms-simplicity-distribution/blob/master/composer.json not to TYPO3. Basically I'm basically following your approach and including Ecodev approach. However, now that you mentioned it, could be great if you put some examples of other versions able to set into branch option since I'm not able ot use a different one that TYPO3_6-2

**Comment by xf-** [comment]
currently it works, i think this is something we can think about in 7 LTS.
