### ISSUE TITLE
[FEATURE] Symlink improvments & htaccess

### ISSUE THREAD

**Issue by Madii** [FluidTYPO3/FluidTYPO3-Vagrant#9]
Hey,

i wrote some improvments for the vagrant setup. Added the one missing symlink and the htaccess file ;-)

https://gist.github.com/Madii/848bd7f3386dcafe1158#file-init-pp

**Comment by xf-** [comment]
hi, 

you can ignore the htaccess.
It is nginx - no htaccess support.

which symlink is missing?

**Comment by Madii** [comment]
Ahhh learned something new. Didn't know that nginx don't support .htaccess. If i see it right this symlink is missing
-> /bin/ln -sf typo3_${typo3_branch} typo3_src 
It's the source symlink.

**Comment by xf-** [comment]
This would only cause trouble.
I load it directly in typo3_src and is also a lot friendlier in my IDE (indexing before the exclude). I can always switch branch in git checkout. This is no tar.gz single version.
